In [8]:
%matplotlib inline
from sklearn.feature_extraction import DictVectorizer
import csv
from sklearn import preprocessing
from sklearn import tree
from sklearn.externals.six import StringIO
import os
allElectronicsData=open(r'/home/zhuangwu/PycharmProjects/learnProject/learn.csv','rb')
reader=csv.reader(allElectronicsData)
headers=reader.next()
print(headers)
featureList=[]
labelList=[]
for row in reader:
    print(row)
    labelList.append(row[len(row)-1])
    rowDict={}
    for i in range(1,len(row) -1 ):
        rowDict[headers[i]]=row[i]
    featureList.append(rowDict)
print(featureList)

['RID', 'age', 'income', 'student', 'credit_rating', 'Class_buys_computer']
['1', 'youth', 'high', 'no', 'fair', 'no']
['2', 'youth', 'high', 'no', 'excellent', 'no']
['3', 'middle_aged', 'high', 'no', 'fair', 'yes']
['4', 'senior', 'medium', 'no', 'fair', 'yes']
['5', 'senior', 'low', 'yes', 'fair', 'yes']
['6', 'senior', 'low', 'yes', 'excellent', 'no']
['7', 'middle_aged', 'low', 'yes', 'excellent', 'yes']
['8', 'youth', 'medium', 'no', 'fair', 'no']
['9', 'youth', 'low', 'yes', 'fair', 'yes']
['10', 'senior', 'medium', 'yes', 'fair', 'yes']
['11', 'youth', 'medium', 'yes', 'excellent', 'yes']
['12', 'middle_aged', 'medium', 'no', 'excellent', 'yes']
['13', 'middle_aged', 'high', 'yes', 'fair', 'yes']
['14', 'senior', 'medium', 'no', 'excellent', 'no']
[{'credit_rating': 'fair', 'age': 'youth', 'student': 'no', 'income': 'high'}, {'credit_rating': 'excellent', 'age': 'youth', 'student': 'no', 'income': 'high'}, {'credit_rating': 'fair', 'age': 'middle_aged', 'student': 'no', 'income

In [9]:
vec=DictVectorizer()

In [10]:
dummyX=vec.fit_transform(featureList).toarray()

In [11]:
print("dummyX:"+str(dummyX))
print(vec.get_feature_names())
print("labellist:"+str(labelList))

dummyX:[[ 0.  0.  1.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  1.  0.  1.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  1.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  0.  1.  0.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.  0.  0.  1.  1.  0.]
 [ 0.  0.  1.  0.  1.  0.  1.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  1.  0.  0.  0.  1.  0.  1.]
 [ 1.  0.  0.  1.  0.  0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  1.  1.  0.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  0.  0.  1.  1.  0.]]
['age=middle_aged', 'age=senior', 'age=youth', 'credit_rating=excellent', 'credit_rating=fair', 'income=high', 'income=low', 'income=medium', 'student=no', 'student=yes']
labellist:['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']


In [12]:
lb=preprocessing.LabelBinarizer()
dummyY=lb.fit_transform(labelList)
print("dummyY:"+str(dummyY))

dummyY:[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [13]:
clf=tree.DecisionTreeClassifier(criterion='entropy')
clf=clf.fit(dummyX,dummyY)
print("clf:"+str(clf))

clf:DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')


In [23]:
with open("lern.dot","w") as f:
    f=tree.export_graphviz(clf,feature_names=vec.get_feature_names(),out_file=f)
oneRowX=dummyX[0,:]
print("oneRowX:"+str(oneRowX))
newRowX = oneRowX
newRowX[0]=1
newRowX[2]=0
print("newRowX:"+str(newRowX))
predictedY=clf.predict(newRowX)
print("predictedY:"+str(predictedY))

oneRowX:[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
newRowX:[ 1.  1.  0.  1.  1.  1.  1.  1.  1.  1.]
predictedY:[1]


/home/zhuangwu/virtualenv/pandas_venv/local/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
